apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-aws-eks-deployment
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: aws-eks-deployment
  template:
    metadata:
      labels:
        app: aws-eks-deployment
    spec:
      containers:
      - name: aws-eks-deployment
        image: debopriyoroy/aws-eks-deployment
        ports:
        - containerPort: 8080  

---
apiVersion: v1
kind: Service
metadata:
  name: project-aws-eks-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"  # ← add this
spec:
  type: LoadBalancer
  selector:
    app: aws-eks-deployment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
